parameters:
  PageNumberParam:
    name: pageNumber
    in: query
    description: Page Number
    schema: 
      type: integer
      format: int64
      default: 1

  PageSizeParam:
    name: pageSize
    in: query
    description: Page Size
    required: false
    schema:
      type: integer
      format: int64
      default: 25   

  CustomerIdParam:
    name: customerId
    in: path
    description: Customer Id
    required: true
    schema:
      type: string
      format: uuid

  BeerIdParam:
    name: beerId
    in: path
    required: true
    description: Beer Id
    schema:
      type: string
      format: uuid
